#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-findbugs
Version  : 2.0.1
Release  : 1
URL      : https://github.com/findbugsproject/findbugs/archive/2.0.1.tar.gz
Source0  : https://github.com/findbugsproject/findbugs/archive/2.0.1.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/com/google/code/findbugs/findbugs/2.0.1/findbugs-2.0.1.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/com/google/code/findbugs/findbugs/2.0.1/findbugs-2.0.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : AML Apache-2.0 BSD-2-Clause BSD-3-Clause CC-BY-2.5 GPL-2.0 LGPL-2.1 OLDAP-2.0
Requires: mvn-findbugs-data = %{version}-%{release}
Requires: mvn-findbugs-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-mvn

%description
Put the jar files for FindBugs plugins in this directory.
For example, you can download the fb-contrib plugin from:
http://fb-contrib.sourceforge.net/

%package data
Summary: data components for the mvn-findbugs package.
Group: Data

%description data
data components for the mvn-findbugs package.


%package license
Summary: license components for the mvn-findbugs package.
Group: Default

%description license
license components for the mvn-findbugs package.


%prep
%setup -q -n findbugs-2.0.1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-findbugs
cp eclipsePlugin-test/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/eclipsePlugin-test_LICENSE.txt
cp findbugs/lib/LICENSE_AppleJavaExtensions.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_lib_LICENSE_AppleJavaExtensions.txt
cp findbugs/licenses/LICENSE-ASM.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-ASM.txt
cp findbugs/licenses/LICENSE-AppleJavaExtensions.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-AppleJavaExtensions.txt
cp findbugs/licenses/LICENSE-bcel.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-bcel.txt
cp findbugs/licenses/LICENSE-commons-lang.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-commons-lang.txt
cp findbugs/licenses/LICENSE-dom4j.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-dom4j.txt
cp findbugs/licenses/LICENSE-jFormatString.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-jFormatString.txt
cp findbugs/licenses/LICENSE-jaxen.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-jaxen.txt
cp findbugs/licenses/LICENSE-jcip.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-jcip.txt
cp findbugs/licenses/LICENSE-jdepend.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-jdepend.txt
cp findbugs/licenses/LICENSE-jsr305.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-jsr305.txt
cp findbugs/licenses/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE.txt
cp findbugs/src/gui/edu/umd/cs/findbugs/gui2/help/License.html %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_src_gui_edu_umd_cs_findbugs_gui2_help_License.html
cp findbugs/src/java/edu/umd/cs/findbugs/gui/help/License.html %{buildroot}/usr/share/package-licenses/mvn-findbugs/findbugs_src_java_edu_umd_cs_findbugs_gui_help_License.html
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/code/findbugs/findbugs/2.0.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/google/code/findbugs/findbugs/2.0.1/findbugs-2.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/code/findbugs/findbugs/2.0.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/google/code/findbugs/findbugs/2.0.1/findbugs-2.0.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/google/code/findbugs/findbugs/2.0.1/findbugs-2.0.1.jar
/usr/share/java/.m2/repository/com/google/code/findbugs/findbugs/2.0.1/findbugs-2.0.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-findbugs/eclipsePlugin-test_LICENSE.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_lib_LICENSE_AppleJavaExtensions.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-ASM.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-AppleJavaExtensions.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-bcel.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-commons-lang.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-dom4j.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-jFormatString.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-jaxen.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-jcip.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-jdepend.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE-jsr305.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_licenses_LICENSE.txt
/usr/share/package-licenses/mvn-findbugs/findbugs_src_gui_edu_umd_cs_findbugs_gui2_help_License.html
/usr/share/package-licenses/mvn-findbugs/findbugs_src_java_edu_umd_cs_findbugs_gui_help_License.html
